# Generated by Django 3.0.3 on 2020-03-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='senha',
            field=models.CharField(help_text='Inform your last senha', max_length=50, verbose_name='Senha'),
        ),
    ]
