# Generated by Django 3.0.3 on 2020-03-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200302_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nome',
            field=models.CharField(help_text='Inform your name', max_length=50, verbose_name='Nome'),
        ),
    ]
