# Generated by Django 3.0.3 on 2020-03-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200304_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Indica que usuário consegue acessar este site de administração.', verbose_name='membro da equipe'),
        ),
    ]
