# Generated by Django 3.0.3 on 2020-03-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20200305_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='foto',
            field=models.FileField(default=1, help_text='Escolha uma imagen', upload_to='img/', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
